#!/usr/bin/env ruby
# This is not actually required by the actual library
# loads the bundled environment
require 'rubygems'

begin
  require 'bundler/setup'
rescue LoadError
  # Let's not complain if bundler isn't around
end

base  = File.basename($0)
paths = ENV['PATH'].split(File::PATH_SEPARATOR)
here  = File.expand_path(File.dirname(__FILE__))

gem_stub = paths.find do |path|
  path = File.expand_path(path)

  next if path == here

  File.exist?("#{path}/#{base}")
end

if gem_stub
  load "#{gem_stub}/#{base}"
else
  abort "The gem stub #{base} could not be found"
end